### ISSUE TITLE
[FEAT] Authentication Page -> Success page for magic link 

### ISSUE THREAD

**Issue by Justfemi** [hngprojects/hng_boilerplate_remix#17]
### Description
Implement the successful login with magic link page as shown in the design

### Acceptance Criteria
- Responsive across all screen sizes (desktop, tablet and mobile)
- Write tests for your code.
- Use components where necessary (header, footer, buttons, modal and so on)

[Link to Design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2-938&t=p2gECcZQmYqvvrn7-4)

### Preview
![image](https://github.com/user-attachments/assets/9bea3171-0e29-409e-acd7-e7421aa9c086)

**Comment by oyin-systems** [comment]
Hi @Justfemi, I noticed that the Figma file only includes the design for the desktop view. Should I proceed with creating the responsive designs for mobile and tablet views based on the desktop layout?

Also, I have already created the header and footer components. Is it okay to use these, or is someone else assigned to work on them?

Thanks!
