### ISSUE TITLE
[Feature]: Develop FAQ Page with already developed FAQs Component and Additional Questions Form

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_remix#50]
Description
Develop an FAQ page that integrates:

- The FAQs component developed by another intern, displaying frequently asked questions retrieved from backend API endpoints / Static data.
- The Additional Questions form previously developed by another intern, allowing users to submit specific inquiries or questions not covered in the FAQs.
### - Acceptance Criteria

- [ ]  Integrate the FAQs component developed by another intern into the FAQ page
- [ ]  Ensure the FAQs are retrieved and displayed dynamically from backend API endpoints/static
- [ ]  Integrate the Additional Questions form into the FAQ page for users to submit inquiries.
- [ ]  Ensure the FAQ page matches the provided design specifications and is responsive.

Deadline: Saturday 10am

Check #56 #53 for the needed components

Links
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=432-7520&m=dev

![349614468-a9c6e21a-4ce3-4b46-9dc1-48bc2feb0d66](https://github.com/user-attachments/assets/5d62297f-240f-4617-85cd-fbceed581a16)

**Comment by abdulmalikyusuf** [comment]
Hi Walt! I am reaching to enquire about the state of this issue, my component relies on your page to be displayed

**Comment by Waltxcodes** [comment]
Was actually waiting for those I relied on their components
